// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team138.robot.subsystems;

import org.usfirst.frc.team138.robot.RobotMap;
import org.usfirst.frc.team138.robot.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Mantis extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid azimouth = RobotMap.mantisAzimouth;
    DoubleSolenoid extension = RobotMap.mantisExtension;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void hugOpen()
    {
    	azimouth.set( DoubleSolenoid.Value.kOff );
    	azimouth.set( DoubleSolenoid.Value.kForward );

    }
    
    public void hugClose()
    {
    	azimouth.set( DoubleSolenoid.Value.kOff );
    	azimouth.set( DoubleSolenoid.Value.kReverse );

    }
    
    public void in()
    {
    	extension.set( DoubleSolenoid.Value.kOff );
    	extension.set( DoubleSolenoid.Value.kForward );

    }
    
    public void out()
    {
    	extension.set( DoubleSolenoid.Value.kOff );
    	extension.set( DoubleSolenoid.Value.kReverse );

    }
}

